authors:
  - Ravinder Reddy (@chinthalapalli)
  - Wojciech Wypior (@wojtek0806)
dependencies:
  ansible.netcommon: ">=2.0.0"
description: F5 BIG-IP Declarative Collection for Ansible
documentation: https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/module_index.html
homepage: https://clouddocs.f5.com/products/orchestration/ansible/devel/
issues: https://github.com/F5Networks/f5-ansible-bigip/issues
license:
  - GPL-3.0-only
name: f5_bigip
namespace: f5networks
readme: README.md
build_ignore:
  - tests/__pycache__
  - tests/compat
  - tests/mock
  - tests/modules
  - tests/module_utils
  - tests/modules
  - tests/plugins
  - tests/utils
  - tests/*.ini
  - tests/*.py
  - changelogs/*
repository: https://github.com/F5Networks/f5-ansible-bigip
tags:
  - f5
  - networking
  - bigip
  - bigiq
version: 3.14.0
